export const projectsData = [
  {
    title: "Example",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image1: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image2: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
  },
  {
    title: "Example",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image1: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image2: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
  },
  {
    title: "Example",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image1: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image2: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
  },
  {
    title: "Example",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image1: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image2: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
  },
  {
    title: "Example",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image1: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image2: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
  },
  {
    title: "Example",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image1: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    image2: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
  },
];
