export const projectsData = [
  {
    title: "Exampleee",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    vercel: 'google.com',
    github: 'google.com',
    images: [
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/forest_river.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/forest_river.jpg", import.meta.url).href,
    ],
  },
  {
    title: "Examplee",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    images: [
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    ],
  },
  {
    title: "Example",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    images: [
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    ],
  },
  {
    title: "Exampl",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    images: [
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    ],
  },
  {
    title: "Examp",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    images: [
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    ],
  },
  {
    title: "Exam",
    technologies: "React",
    description: "I don`t know what I'm talking aboutttttttttttttttttttttt s",
    coverImage: new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    images: [
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
      new URL("./ImageSearch/cube_dark.jpg", import.meta.url).href,
    ],
  },
];
